# Generated by Django 5.0 on 2023-12-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='headline',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
