# Generated by Django 5.0 on 2023-12-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jobseeker_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='job_time',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time')], default='Full-time', max_length=15),
        ),
    ]
