# Generated by Django 5.0 on 2023-12-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jobseeker_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='main_services',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
