# Generated by Django 5.0 on 2023-12-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_recruiter_main_services_recruiter_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
