# Generated by Django 5.0 on 2023-12-20 16:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_jobpost_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='company_cover_photo',
            field=models.ImageField(null=True, upload_to=core.models.company_cover_image_upload_path, verbose_name='Company Cover Photo'),
        ),
    ]
