# Generated by Django 5.0 on 2023-12-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_recruiter_company_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
