# Generated by Django 5.0 on 2023-12-21 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_jobseeker_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationjobseeker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jobseeker'),
        ),
    ]
