# Generated by Django 5.0 on 2023-12-21 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_applicationjobseeker_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationjobseeker',
            old_name='user',
            new_name='jobseeker',
        ),
    ]
