# Generated by Django 5.0 on 2023-12-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_applicationjobseeker_jobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
