# Generated by Django 5.0 on 2024-01-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_jobpost_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='total_employees',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
