# Generated by Django 5.0 on 2024-01-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_recruiter_total_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationjobseeker',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
