# Generated by Django 5.0 on 2024-01-14 17:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_applicationjobseeker_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='job_requirements',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='job_responsibilities',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='skills_required',
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='about_this_job',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
