# Generated by Django 5.0 on 2024-01-14 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_jobpost_job_requirements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
